# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 19:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('login', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('point', geoposition.fields.GeopositionField(max_length=42)),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_passenger_end', to='course_work.Location')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_passenger_start', to='course_work.Location')),
            ],
        ),
        migrations.CreateModel(
            name='Road',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('end', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_road_end', to='course_work.Location')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_road_start', to='course_work.Location')),
            ],
        ),
    ]
