# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 21:52
from __future__ import unicode_literals

import string

from django.db import migrations, models
import django.db.models.deletion
import geoposition.fields
import random
import string

from course_work.models import Location


def gen_locations(apps, schema_editor):
    rand_str = lambda n: ''.join([random.choice(string.ascii_lowercase) for i in range(n)])
    for i in range(10):
        loc = Location(name = rand_str(8))
        loc.save()

class Migration(migrations.Migration):

    dependencies = [ ('course_work', '0001_initial'),
    ]

    operations = [ migrations.RunPython(gen_locations, reverse_code=migrations.RunPython.noop),
    ]
