# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 21:52
from __future__ import unicode_literals

from django.db import migrations
import random
import string

from course_work.models import Location, Road


def gen_roads(apps, schema_editor):
    locs = Location.objects.all()
    for i in range(40):
        road = Road(time = random.randint(1, 10))
        road.start = random.choice(locs)
        road.end = random.choice(locs)
        road.save()

class Migration(migrations.Migration):

    dependencies = [ ('course_work', '0002_gen_locations'),
    ]

    operations = [ migrations.RunPython(gen_roads, reverse_code=migrations.RunPython.noop),
    ]
