# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-07 21:52
from __future__ import unicode_literals

from django.db import migrations
import random
import string

from course_work.models import Location, Road, Passenger


def gen_passengers(apps, schema_editor):
    locs = Location.objects.all()
    rand_str = lambda n: ''.join([random.choice(string.ascii_lowercase) for i in range(n)])
    list_date = ['2017-08-04', '2017-05-01', '2017-08-01']
    for i in range(15):
        passenger = Passenger(name = rand_str(5)+' '+rand_str(7))
        passenger.start = random.choice(locs)
        passenger.end = random.choice(locs)
        passenger.price = random.randint(500, 2500)
        passenger.date = random.choice(list_date)
        passenger.save()

class Migration(migrations.Migration):

    dependencies = [ ('course_work', '0003_gen_roads'),
    ]

    operations = [ migrations.RunPython(gen_passengers, reverse_code=migrations.RunPython.noop),
    ]
